Repro of non-unification in definition of joinMap
Still a WIP, opening as draft to showcase an issue I described on Zulip.

```
> cargo test -p test_gen gen_list::list_join_map -- --nocapture
...
running 1 test
[compiler/can/src/builtins.rs:2186] "list_list_b: {}" = "list_list_b: {}"
[compiler/can/src/builtins.rs:2186] list_list_b.index() = 127
thread 'gen_list::list_join_map' panicked at 'Roc failed with message: "UnresolvedTypeVar: 127 at compiler/mono/src/ir.rs line 3987"', compiler/test_gen/src/gen_list.rs:2216:5
test gen_list::list_join_map ... FAILED
```

We can see from the error message that `list_list_b` is not resolved,
even though once we have the concrete typings for the arguments to
`joinMap` as

```
ARG_1: List TA
ARG_2: TA -> List TB
```

we should, in principle, have generated the constraints

```
// from List.map : List before, (before -> after) -> List after

List before = List TA
before -> after = TA -> List TB
List after = list_list_b
```

which should solve to

```
before = TA
after = List TB
list_list_b = List (List TB)
```

So it seems like the type of `ListMap` in `RunLowLevel` is not being
considered during typechecking?